version: '3.3'
services:
  app:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    container_name: asesorias-container
    image: asesorias-image
    ports:
      - "8080:8080"
    restart: always