version: '3.8'
services:
  app:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0
    container_name: asesorias-container
    image: asesorias-image
    ports:
      - "8080:8000"